### ISSUE TITLE
[REMOVAL] Vanilla Cookie Manager

### ISSUE THREAD

**Issue by magical-heyrovsky** [Lissy93/awesome-privacy#116]
### Title

Vanilla Cookie Manager

### Removal Reason

Deprecated: https://github.com/laktak/vanilla-chrome

### Association Disclosure

No association

### Would you like to submit a PR?

No.

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by ltGuillaume** [comment]
@magical-heyrovsky Good point. Created pull request #117
