### ISSUE TITLE
[ADDITION] Mojeek

### ISSUE THREAD

**Issue by atomGit** [Lissy93/awesome-privacy#119]
### Category

Non-Tracking Search Engines

### Software to be added

There are *very few* independent, privacy respecting search engines that don't manipulate results and [Mojeek](https://www.mojeek.com/) is one of them

most of the so-called alternative search engines (DDG, Startpage, etc.) are not true search engines - they are essentially proxies that rely on Bing or Google for results

Mojeek is a very promising search engine that has their own index with somewhere over 6 billion pages indexed as of this writing and its founders seem to be very ethical - i've gotten to know them a bit as a result of providing feedback on their community site (they are very open to suggestions)

### Supporting Material

* [Mojeek](https://www.mojeek.com/)
* [About Mojeek - building the world's alternative search engine](https://www.mojeek.com/about/)
* [Mojeek Privacy Policy](https://www.mojeek.com/about/privacy/)
* [Mojeek Terms of Service](https://www.mojeek.com/about/terms.html)
* [The Mojeek Discourse - Alternative search engine, alternative community.](https://community.mojeek.com/)

### Association Disclosure

i've provided feedback but am not an employee

### Would you like to submit a PR?

No.

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by ltGuillaume** [comment]
@atomGit Why did you close this?

**Comment by atomGit** [comment]
i didn't realize there's already a [request](https://github.com/Lissy93/awesome-privacy/issues/87) to add mojeek
