### ISSUE TITLE
[ADDITION] Thunderbird

### ISSUE THREAD

**Issue by atomGit** [Lissy93/awesome-privacy#120]
### Category

Encrypted Email

### Software to be added

Thunderbird has built-in encryption tools for a while now (no add-on needed) and it makes encryption very easy to use

### Supporting Material

* [Mozilla Thunderbird - Standards support](https://en.wikipedia.org/wiki/Mozilla_Thunderbird#Standards_support)
* [Mozilla Thunderbird - Security](https://en.wikipedia.org/wiki/Mozilla_Thunderbird#Security)

### Association Disclosure

negitive

### Would you like to submit a PR?

No.

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Already added via https://github.com/Lissy93/awesome-privacy/commit/fd3bea97580165716c0606ae2e2df22301c5ce4a
