### ISSUE TITLE
[AMENDMENT] Browsers - busted link

### ISSUE THREAD

**Issue by atomGit** [Lissy93/awesome-privacy#143]
### Title

Browsers > Firefox

### Amendments

link for 12bytes is busted...

> For a though config, see @arkenfox's user.js. You can also follow one of these guides by: Restore Privacy or **12Bytes**

i publish 2 guides - both can be found here: [Everything Firefox – 12Bytes.org](https://12bytes.org/articles/tech/firefox/) (along with a lot of other FF junk)

direct links:
* [The Firefox Privacy Guide for Dummies! – 12Bytes.org](https://12bytes.org/articles/tech/firefox/the-firefox-privacy-guide-for-dummies/)
* [Firefox Configuration Guide for Privacy Freaks and Performance Buffs – 12Bytes.org](https://12bytes.org/articles/tech/firefox/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs/)

the 'Privacy Freaks' guide linked to from my site is actually published on Codeberg: [12bytes.org/firefox-config-guide: Firefox Configuration Guide for Privacy Freaks and Performance Buffs - firefox-config-guide - Codeberg.org](https://codeberg.org/12bytes.org/firefox-config-guide)

### Association Disclosure

no

### Would you like to submit a PR?

None

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the project the amendment refers to
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Somewhat related https://github.com/Lissy93/awesome-privacy/issues/194. Please feel free to re-open it if I am mistaken.
