### ISSUE TITLE
[ADDITION] MoneyManager Ex

### ISSUE THREAD

**Issue by DavidBeegle** [Lissy93/awesome-privacy#160]
### Category

Money Management

### Software to be added

Open-source, cross-platform, software that helps you organize your finances and keep track of where, when and to who the money goes. It is also a great tool to get a bird's eye view of your financial worth.

### Supporting Material

https://moneymanagerex.org/

### Association Disclosure

No association

### Would you like to submit a PR?

None

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
MoneyManager Ex is already added under notable mentions of **Secure Budgeting**
