### ISSUE TITLE
[REMOVAL] DN66 (without typo: DNS66)

### ISSUE THREAD

**Issue by thomasmerz** [Lissy93/awesome-privacy#166]
### Title

Ad Blockers

### Removal Reason

This project uses old and not working or very slow DNS servers and seems not to be maintained any more (sinca may 2022) :-(
I already opened an [issue](https://github.com/julian-klode/dns66/issues/484) there, but no answer/reaction yet…

### Association Disclosure

I never had or have any association with this project.

### Would you like to submit a PR?

Maybe?

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Thanks for the issue. Removed in https://github.com/Lissy93/awesome-privacy/pull/276
