### ISSUE TITLE
[AMENDMENT] JMP.chat out of beta

### ISSUE THREAD

**Issue by singpolyma** [Lissy93/awesome-privacy#168]
### Title

JMP.chat

### Amendments

No longer in beta, new pricing https://blog.jmp.chat/b/launch-2023

### Association Disclosure

Yes

### Would you like to submit a PR?

None

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the project the amendment refers to
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Related https://github.com/Lissy93/awesome-privacy/issues/245
Done in https://github.com/Lissy93/awesome-privacy/pull/275
