### ISSUE TITLE
[REMOVAL] snibox

### ISSUE THREAD

**Issue by WardPearce** [Lissy93/awesome-privacy#176]
### Title

snibox

### Removal Reason

Has not been updated in 4 years.

### Association Disclosure

Creator of Paaster

### Would you like to submit a PR?

Yes!

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Closing this as snibox is already removed.
