### ISSUE TITLE
[ADDITION] Proton Pass

### ISSUE THREAD

**Issue by gabrielvicenteYT** [Lissy93/awesome-privacy#177]
### Category

Password Managers

### Software to be added

I want Proton Pass to be added, since it has a privacy-friendly policy, and is open-source.

### Supporting Material

https://proton.me/pass
https://github.com/protonpass

### Association Disclosure

I do not have any association with Proton Passm aside from using it.

### Would you like to submit a PR?

Maybe?

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
+1 I agree
Would you be up for submitting a PR? Otherwise I can add it later on.

**Comment by gabrielvicenteYT** [comment]
> +1 I agree Would you be up for submitting a PR? Otherwise I can add it later on.

I can submit one, but I'm a bit lazy.

**Comment by Lissy93** [comment]
Added.
