### ISSUE TITLE
[CONTENT-CHANGE] Add Pirsch Analytics

### ISSUE THREAD

**Issue by Kugelschieber** [Lissy93/awesome-privacy#19]
Thanks for making this list!

### Explain why it should be added
Pirsch is a privacy-friendly and [open-source](https://github.com/pirsch-analytics/pirsch) alternative to Google Analytics.

### Additional Context
Privacy Respecting Software > Bonus Lissy93/personal-security-checklist#1 - Alternatives to Google > Analytics

I've started this as a personal project for my own website. Find out more here: https://pirsch.io/blog/introduction/

### Content (optional)
The website: https://pirsch.io

**Comment by Lissy93** [comment]
Hiya @Kugelschieber 
I'm very sorry for the long delay...
I've taken a look at your project, it looks awesome, and definitely meets the requirements.
I've added it to the list, but in this new privacy software repo, which will soon become the home of the software section from personal-security-checklist.
