### ISSUE TITLE
[REMOVAL] Bromite

### ISSUE THREAD

**Issue by advait404** [Lissy93/awesome-privacy#192]
### Title

Bromite

### Removal Reason

Bromite has not received any updates in a long time (over 9 months) and most likely has several security vulnerabilities. 

### Association Disclosure

NA

### Would you like to submit a PR?

Maybe?

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Done in https://github.com/Lissy93/awesome-privacy/pull/278
