### ISSUE TITLE
[ADDITION] Cromite

### ISSUE THREAD

**Issue by advait404** [Lissy93/awesome-privacy#193]
### Category

Cromite

### Software to be added

Cromite is a fork of bromite which is up-to-date and has some additional features 

### Supporting Material

https://github.com/uazo/cromite

### Association Disclosure

NA

### Would you like to submit a PR?

Maybe?

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software / service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Already added via https://github.com/Lissy93/awesome-privacy/pull/244
