### ISSUE TITLE
[AMENDMENT] broken link corrections

### ISSUE THREAD

**Issue by atomGit** [Lissy93/awesome-privacy#194]
### Title

general

### Amendments

* (2 instances) `https://12bytes.org/7750` > `https://12bytes.org/the-firefox-privacy-guide-for-dummies/`
* `https://12bytes.org/articles/tech/firefox/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs/` > `https://codeberg.org/12bytes/firefox-config-guide`
* `https://12bytes.org/articles/tech/alternative-search-engines-that-respect-your-privacy/` > `https://12bytes.org/alternative-search-engines-that-are-more-respectful-of-your-privacy/`

### Would you like to submit a PR?

None

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with the project the amendment refers to
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software / service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
The links are either removed or updated during the PR.
