### ISSUE TITLE
[REMOVAL] Bromite

### ISSUE THREAD

**Issue by nolesapex** [Lissy93/awesome-privacy#197]
### Title

Bromite should be removed due to no longer being maintained.

### Removal Reason

When it comes to privacy, services offering privacy tools and improvements to the user experience should remain up to date. Unfortunately, Bromite appears to have not been updated since 2022, according to the releases on Bromite's GitHub, where the latest Bromite release is from that year. This lack of recent updates raises concerns about its security.

Upon further research, I came across a website blog where the author explains their concerns with Bromite.

Quote from the article:

"The Bromite situation raises questions about how open-source projects should respond when big contributors or maintainers unexpectedly leave. If possible, communication from Carl could have prevented months of confusion. The absence of updates on the Bromite website suggests that Carl is the sole person with access to the page, as well as the Patreon fund and crypto wallets, which receive donations to support development costs. Having a second trusted project maintainer with access to these resources could have alerted potential users to the project's status and prevented the loss of donated funds.

In the meantime, Bromite users should consider using Bromite builds from Uazo's buildtools repo or explore alternative browsers for enhanced security. Bromite is just one of many open-source software projects used daily by millions, and Carl Sagan's absence from the project underscores the value that these developers and maintainers provide for free."

I strongly urge the maintainers of the Awesome Privacy site to remove Bromite from the browser suggestion listing.

### Would you like to submit a PR?

None

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Done in https://github.com/Lissy93/awesome-privacy/pull/278.
