### ISSUE TITLE
[ADDITION] Add Wormhole

### ISSUE THREAD

**Issue by feross** [Lissy93/awesome-privacy#2]
### Explain why it should be added
[A clear and concise description of the point and why it should be added to the list.]

Thanks for including FilePizza and Instant.io as recommendations for file transfer in the list. (I'm the creator of WebTorrent, which both of those services use!) Instant.io is actually run by me and the WebTorrent team :)

While I recommend both of those services, one shortcoming is that they don't use end-to-end encryption. That's why we built Wormhole (https://wormhole.app/) to fill that gap. I recommend Wormhole over the other services these days.

### Additional Context
[Provide some context, with a bit of detail. Specify which of the 10 categories this point should be listed under]

[Wormhole](https://wormhole.app/) should go into the "File Drop" category.

### Content (optional)
[Suggest some content, including links, written in clear English for the point you'd like added]

[Wormhole](https://wormhole.app/) lets you share files with end-to-end encryption and a link that automatically expires. So you can keep what you share private and make sure your stuff doesn't stay online forever. Wormhole uses end-to-end encryption to protect your files so they can never be shared or viewed by anyone but you and the intended recipients. Files are permanently deleted from the server after 24 hours. Wormhole encrypts all files with 128-bit AES-GCM encryption before they leave the browser. You can read more about the [security design](https://wormhole.app/security) to learn more.

---

### NOTES:
- Before submitting, check that there isn't a similar open issue already 
- Please create a new issue for each separate/ stand-alone point you'd like added to the list
- If you are confident in your abilities, you can also write the point yourself, and submit it as a PR
- Thank you for your suggestion, it's because of contributors like yourself that this project can exist

**Comment by Lissy93** [comment]
Closing, as presumably not open source.
