### ISSUE TITLE
[REMOVAL] Skiff

### ISSUE THREAD

**Issue by titanism** [Lissy93/awesome-privacy#210]
### Title

Skiff

### Removal Reason

Hi there - you can remove Skiff from your list since they are now defunct and closing down in 6 months  <https://twitter.com/skiffprivacy/status/1756093174806974831> <https://skiff.com/data-migration>

### Would you like to submit a PR?

None

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by berndwa** [comment]
Skiffprivacy is joining Notion - so in the future it's only Skiff w/o privacy 👎🏻
