### ISSUE TITLE
[REMOVAL] Consider removing or further discourage the use of Authy

### ISSUE THREAD

**Issue by ltguillaume** [Lissy93/awesome-privacy#214]
### Title

Authy

### Removal Reason

Reasons already stated:
- Authy is proprietary
- Increased attack surface due to cloud sync

Further developments:
- Authy already has been hacked, leaking user data (August 2022)
- Vendor lock-in: a complete lack of export features, even though there _used to be_ a way (https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93) and the risk of completely getting yourself locked out of your accounts if you delete your Authy account: https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93?permalink_comment_id=4829538#gistcomment-4829538
- The discontinuation of their desktop solutions (March 19), even earlier than previously announced (August)
- Uncertain future of the company: several rounds of significant amounts of layoffs have been seen over the last few years

### Association Disclosure

None

### Would you like to submit a PR?

No.

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Thanks @ltguillaume :)
