### ISSUE TITLE
[ADDITION] GIMP (Complete)

### ISSUE THREAD

**Issue by CrazyWolf13** [Lissy93/awesome-privacy#220]
### Category

Creativity

### Listing Name

Gnu Image Manipulation Program (GIMP)

### Listing URL

https://www.gimp.org/

### Listing Icon

https://www.gimp.org/images/wilber32.png

### Listing Description

GIMP (GNU Image Manipulation Program) is a leading open-source software for graphic design and image editing. With a user-friendly interface and a wide range of features, it offers powerful editing capabilities for both beginners and professionals. GIMP prioritizes user privacy by being transparent with its source code, ensuring that user data remains secure. As a free and continually evolving platform, GIMP provides a creative sanctuary where users can express themselves without compromising their privacy.

### GitHub repository

https://gitlab.gnome.org/GNOME/gimp

### Is Open Source?

- [X] Yes, it's open source

### Security Audited?

- [ ] Yes, it's been security audited

### Accepts Anon Payment?

- [ ] Yes, accept anonymous payment

### Justification and Further Info

Supports donation to be marked as anonymous, liberapay is supported, funded by GNU.

### Final Checklist

- [X] I confirm that I've read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I have clearly declared any affiliation I may have with this service

**Comment by Lissy93** [comment]
Good shout, I'll add that - love Gimp :)

**Comment by Lissy93** [comment]
Thanks again, have added Gimp in afc1bdd

---

Have also completed the rest of the Image Editors section:
-Website: https://awesome-privacy.xyz/creativity/image-editors
-Readme: https://github.com/Lissy93/awesome-privacy#image-editors

https://github.com/Lissy93/awesome-privacy/blob/7f53ea4ed0dcebfedb6a11b990df6d775be9e325/awesome-privacy.yml#L4806-L4889

**Comment by CrazyWolf13** [comment]
Looks very good! 
Thanks!
Yeah, love open-source as well.
