### ISSUE TITLE
[QUESTION] What do you think about using Bitwarden for 2-factor authentication?

### ISSUE THREAD

**Issue by marcqw** [Lissy93/awesome-privacy#225]
### Your Question

Hello and thanks for this awesome job.

Just a simple and quick question: Bitwarden is recommend as a good password manager. What do you think about using it  for 2-factor authentication?

Thanks for your clarification :)

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] A similar question has not already [been asked](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software / service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Yeah, I agree with @ltguillaume - having passwords and 2FA codes in the same place defeats the objective of 2FA, if your password manager was (god forbid) ever compromised. Still better than no 2FA, but I personally just use a separate app.
