### ISSUE TITLE
[REMOVAL] Samourai Wallet

### ISSUE THREAD

**Issue by romaincabirol** [Lissy93/awesome-privacy#239]
### Title

**Samourai Wallet** (source: [Finance ➜ Crypto Wallets ➜ Samourai Wallet](https://github.com/Lissy93/awesome-privacy/tree/main#crypto-wallets))

### Removal Reason

As shown on the official website, it has been seized after the founder have been arrested and charged with money laundering. 

### Removal Data

```yaml
name: Samourai Wallet
url: https://samouraiwallet.com/
description: >
  An open-source, Bitcoin-only privacy-focused wallet, with some innovative
  features. Samourai Wallet works under any network conditions, with a full
  offline mode, useful for cold storage. It also supports a comprehensive range
  of privacy features including: STONEWALL that helps guard against address
  clustering deanonymization attacks, PayNym which allows you to receive funds
  without revealing your public address for all to see, Stealth Mode which hides
  Samourai from your devices launcher, Remote SMS Commands to wipe or recover
  your wallet if the device is seized or stolen, and Whirlpool which is similar
  to a coin mixer, and OpenDime is also supported for offline USB hardware
  wallets.
followWith: Bitcoin
github: Samourai-Wallet/samourai-wallet-android
```

### Would you like to submit a PR?

Maybe?

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You have read our [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) and software requirements
- [X] You agree to the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Removed in https://github.com/Lissy93/awesome-privacy/pull/270. Thanks for creating the issue @romaincabirol!
