### ISSUE TITLE
[AMENDMENT] Brave Search

### ISSUE THREAD

**Issue by southwindcg** [Lissy93/awesome-privacy#241]
### Title

Brave Search

### Amendments

Brave Search appears in *both* the Search Engines main list *and* the Search Engines Notable Mentions list.

### Would you like to submit a PR?

None

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with the project the amendment refers to
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software / service
- [X] You agree to our [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] You have read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)

**Comment by SadMadLad** [comment]
Made the amendment in https://github.com/Lissy93/awesome-privacy/pull/271. Thanks for the issue @southwindcg
