### ISSUE TITLE
[REMOVAL] Raivo OTP from the list

### ISSUE THREAD

**Issue by dantehemerson** [Lissy93/awesome-privacy#246]
### Title

Raivo OTP

### Removal Reason

The OTP manager app Raivo was [acquired by a company](https://twitter.com/RaivoOTP/status/1683372954002808833?s=20). But have a lot of unsolved questions regarding security and some people lost his data.
There are a lot of opened issues about this: https://github.com/raivo-otp/ios-application/issues. 

### Would you like to submit a PR?

None

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You have read our [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) and software requirements
- [X] You agree to the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Removed in https://github.com/Lissy93/awesome-privacy/commit/ba27593a5dcbfd58b4b9079277c54b0836d183d8
