### ISSUE TITLE
[AMENDMENT] PhotoPea

### ISSUE THREAD

**Issue by 0ryz** [Lissy93/awesome-privacy#264]
### Title

PhotoPea

### Amendments

On the site it says it's open source while it isn't.
![image](https://github.com/user-attachments/assets/037a9c28-2266-48df-aac9-b383daea83f6)

### Affiliation Disclosure

I don't and never had associated with PhotoPea

### Would you like to submit a PR?

No.

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with the project the amendment refers to
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software / service
- [X] You agree to our [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] You have read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)

**Comment by SadMadLad** [comment]
Made the amendment in https://github.com/Lissy93/awesome-privacy/pull/272. Thanks @0ryz
