### ISSUE TITLE
[ADDITION] Picocrypt

### ISSUE THREAD

**Issue by TheGuardianLight** [Lissy93/awesome-privacy#266]
### Category

Picocrypt

### Software to be added

Picocrypt is a very lightweight but powerful utility for encrypting files.

### Supporting Material

https://github.com/HACKERALERT/Picocrypt

### Affiliation Disclosure

I am not or have not been affiliated with this project in any way.

### Would you like to submit a PR?

Maybe?

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software / service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Done in https://github.com/Lissy93/awesome-privacy/pull/296. Thanks!
