### ISSUE TITLE
[REMOVAL]  Site Bleacher

### ISSUE THREAD

**Issue by ltguillaume** [Lissy93/awesome-privacy#289]
### Title

Site Bleacher

### Removal Reason

- Probably doesn't work with Firefox anymore due to (dynamic) first party isolation
- Hasn't been updated in 5 years

### Association Disclosure

None

### Would you like to submit a PR?

No.

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You have read our [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) and software requirements
- [X] You agree to the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Done in https://github.com/Lissy93/awesome-privacy/pull/290. Thank you!
