### ISSUE TITLE
[AMENDMENT] ParrotOS URL has changed

### ISSUE THREAD

**Issue by pantraining** [Lissy93/awesome-privacy#294]
### Title

Parrot

### Amendments

New URL: https://www.parrotsec.org/

### Affiliation Disclosure

Nope

### Would you like to submit a PR?

None

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with the project the amendment refers to
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software / service
- [X] You agree to our [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] You have read and followed the [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md)

**Comment by SadMadLad** [comment]
Done in https://github.com/Lissy93/awesome-privacy/pull/295. Thank you for creating the issue!
