### ISSUE TITLE
[REMOVAL] Simple Mobile Tools

### ISSUE THREAD

**Issue by maxstarkenburg** [Lissy93/awesome-privacy#299]
### Title

Simple Mobile Tools

### Removal Reason

These are currently listed under "Nonorable Mentions" on the [mobile apps page](https://awesome-privacy.xyz/security-tools/mobile-apps). However, they were sold a while back and filled with ads ([link](https://www.androidauthority.com/simple-mobile-tools-acquisition-3391041/), [link](https://github.com/SimpleMobileTools/General-Discussion/issues/241)). If you'd like to replace the mention, https://github.com/FossifyOrg took over as a fork.

### Association Disclosure

I have no affiliation with Simple Mobile Tools (except as a past user and one-time donator) nor with Fossify (except as a user of some of their apps)

### Would you like to submit a PR?

Maybe?

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated whether or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You have read our [Contributing Guide](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) and software requirements
- [X] You agree to the [Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Done. thanks to @ltguillaume https://github.com/Lissy93/awesome-privacy/pull/300
