### ISSUE TITLE
[AMENDMENT] ClamAV

### ISSUE THREAD

**Issue by Starttoaster** [Lissy93/awesome-privacy#31]
### Title

ClamAV

### Amendments

https://github.com/lissy93/awesome-privacy#anti-malware

On the linked page, it lists `CalmAV` instead of `ClamAV`. Only thought to mention it since "Calm" is a real word, it makes it look like this might not have been a typo, when it is.

### Association Disclosure

I have not.

### Would you like to submit a PR?

No.

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the project the amendment refers to
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Oops, a typo. Thanks for raising :)
