### ISSUE TITLE
[ADDITION] Vikunja

### ISSUE THREAD

**Issue by kolaente** [Lissy93/awesome-privacy#35]
### Category

Productivity

### Software to be added

Vikunja is an open-source to-do application (primarily web, there's also a very rudimentary flutter app and CalDAV integration). Similar to Todoist or Trello it lets you organize pretty much everything from a shopping list to a bigger project with multiple collaborators. A highlight are multiple views (List, Gantt, Table, Kanban) to visualize all tasks in different contexts. For collaboration, it has the usual sharing functionalities like team and user sharing but also Link Shares which allow you to share a list with someone else without them requiring an account.

### Supporting Material

Website: https://vikunja.io

### Association Disclosure

I am the creator of Vikunja.

### Would you like to submit a PR?

Yes!

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Heya @kolaente

Vikunja looks awesome, really nice work on it :)

Really useful app,  decent feature set, open source and nicely documented.
I think it'd be a great fit for the list, would you be able to submit a PR?

For the description, some things that would be good to mention:
- that it's open source
- can be self-hosted, or used through managed instance for small fee
- Summary of feature set, (but shouldn't read like an advert)
- Briefly touch on how data is stored, if you think that's relevant


----



And this is nothing that would be a deal breaker, but a couple of questions that I had:
- If the app is self-hosted, by default, are there any external requests made, either to the Vikunja or to any other platforms (CDN, analytics, Sentry, etc)?
- Has there been a security audit on either the hosted instance or source?
- It would be awesome if the privacy policy could list exactly what data is being collected, even the obvious stuff like user-inputed data
- If used through the managed instance, how is both privacy and security of client data maintained? Any encryption?
- And can a paying user export their data, in a standard format (like CalDAV or at least CSV)

**Comment by kolaente** [comment]
PR is up: #36 (I hope that's fine)

About your other questions:

> If the app is self-hosted, by default, are there any external requests made, either to the Vikunja or to any other platforms (CDN, analytics, Sentry, etc)?

By default, there are no other requests. There is a sentry integration which would report issues to the managed service at sentry.io but it is disabled by default.

> Has there been a security audit on either the hosted instance or source?

There hasn't been one yet.

> If used through the managed instance, how is both privacy and security of client data maintained? Any encryption?

The hosted service implements all standard security measures - only a handful people have access to the servers, the servers are kept up-to-date and monitored. Privacy-wise, everything is hosted in the EU and therefore falls under the GDPR privacy laws.

There's no end-to-end encryption but a server drive encryption.

> And can a paying user export their data, in a standard format (like CalDAV or at least CSV)

Yes, there's a data export available which gives users a zip file with all data and lets them move easily to any other Vikunja instance.
