### ISSUE TITLE
[ADDITION] Logseq

### ISSUE THREAD

**Issue by stamatim** [Lissy93/awesome-privacy#40]
### Category

Digital Notes

### Software to be added

[Logseq](https://logseq.com/) is a privacy-first, open-source knowledge base that works on top of local plain-text Markdown and Org-mode files.

### Supporting Material

- Website – https://logseq.com/
- GitHub – https://github.com/logseq/logseq
- Discord – https://discord.com/invite/KpN4eHY
- Forum – https://discuss.logseq.com/
- Documentation – https://docs.logseq.com/#/page/Contents
- Product Roadmap - https://trello.com/b/8txSM12G/logseq-roadmap

### Association Disclosure

I am not associated with the project, however, I am a happy user of the product

### Would you like to submit a PR?

Maybe?

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Thanks @stamatim
Logseq looks awesome, have just been testing it out, looks like a good fit. Thanks for providing all the info.
Will add it now...
