### ISSUE TITLE
[ADDITION] servers.guru

### ISSUE THREAD

**Issue by slade991** [Lissy93/awesome-privacy#44]
### Category

Cloud Hosting

### Software to be added

https://servers.guru

Servers.guru provide cloud hosting (VPS and cloud servers with dedicated CPU resources). It is a reseller with an emphasis on privacy. No private informations beside a working email address are required from the customer if crypto-currencies are used as a payment method. It is also on the lower end of the usually costly alternatives.

### Why it should be added?

It should be added as there is little alternatives in the list and one of them is even a dead link.

### Supporting Material

website is here: https://servers.guru

### Association Disclosure

I'm the funder of servers.guru

### Would you like to submit a PR?

Yes!

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Hi @slade991 
servers.guru looks awesome, nice work! 

Would you be up for submitting a PR? As the description, just summarize what you put as this issue description, (accepts crypto, server locations, affordable, is reseller)

And you're right- there aren't a lot of decent anonymous hosting providers at the moment. You might have me as a new customer very shortly! 

Out of interest, which upstream provider are you using?

I shall also delete Vindo now it's offline...

**Comment by slade991** [comment]
Hey!
Thanks :) i will do the pull request. 
For upstream providers, at the moment we use Hetzner, we are always looking to incorporate new ones, but so far didn't find any other that caught our attention.
We'll be very happy to count you as a customer, if you have any questions don't hesitate to contact me :)
