### ISSUE TITLE
[ADDITION] personalDNSfilter

### ISSUE THREAD

**Issue by ryder203** [Lissy93/awesome-privacy#55]
Hi there. Maybe add our little FOSS app personalDNSfilter (DNS changer / ad- tracking- content-blocker). Cheers, Tobi.

https://www.zenz-solutions.de/personaldnsfilter-wp/

https://github.com/IngoZenz/personaldnsfilter

**Comment by Lissy93** [comment]
Heya, could you follow the issue template please.
As without it there's some important info missing. Importantly the association section (to disclose if your affiliated with the project), and also the 4 checkboxes at the end.
I don't mean to be annoying, it just to keep things consistent and transparent :)
