### ISSUE TITLE
Add FOSS code hosting solutions

### ISSUE THREAD

**Issue by itsnotsaved** [Lissy93/awesome-privacy#6]
### Solution list
- GitLab - https://about.gitlab.com/install/
- Gitea - https://gitea.io/
- Gogs - https://gogs.io/

**Comment by Lissy93** [comment]
Adding now....


- SourceHut - Git and mercurial code hosting, task management, mailing lists, wiki hosting and Alpine-based build pipelines. Can be self-hosted, or used through the managed instance at [sr.ht](https://sr.ht/)
- CodeBerg - A fully-managed instance of Gitea
- Gitea - Lightweight self-hosted git platform, written in Go
- Gogs - Lightweight self-hosted git platform, written in Go


Funnily enough, both [Gitea](https://github.com/go-gitea/gitea) and [Gogs](https://github.com/gogs/gogs) are hosted on.... GitHub 😅
