### ISSUE TITLE
[ADDITION] Photoprism

### ISSUE THREAD

**Issue by kerbless** [Lissy93/awesome-privacy#60]
### Category

Bonus

### Software to be added

PhotoPrism® is an AI-Powered Photos App for the Decentralized Web.
It makes use of the latest technologies to tag and find pictures automatically without getting in your way. You can run it at home, on a private server, or in the cloud. (Source: [photoprism.app](https://photoprism.app/)).

### Supporting Material

[github](https://github.com/photoprism/photoprism)
[website](photoprism.app)
[100% self-funded and indipendent](https://photoprism.app/membership)

### Association Disclosure

Not associated in any way

### Would you like to submit a PR?

Yes!

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Hiya @kerbless :wave:

Thanks for recommending PhotoPrism, I'm actually running it on my homelab, and it really is awesome 

Would you be up for submitting a PR? No worries if not, I'm happy to add it :)

It should probably go under [Bonus #3 - Self-Hosted Services](https://github.com/Lissy93/awesome-privacy#bonus-3---self-hosted-services), as a new bullet point, maybe Media. Note that it's in alphabetical order.

**Comment by Lissy93** [comment]
Yeah :+1: it could also fit there, and with `(Self-Hosted)` added after the title

**Comment by kerbless** [comment]
@Lissy93 Waiting for approval, I also noticed that there is a bit of inconsistency in the markdown file when it comes to empty spaces before headings but maybe this is for another issue.

**Comment by kerbless** [comment]
@Lissy93 Waiting for approval, I also noticed that there is a bit of inconsistency in the markdown file when it comes to empty spaces before headings but maybe this is for another issue.

**Comment by Lissy93** [comment]
Thanks @Kerbless - merged :)

> I also noticed that there is a bit of inconsistency in the markdown file when it comes to empty spaces before headings

Yeah, you're right. I'm going to write a lint workflow and add it to the CI, that will probably be the best way to find, fix and enforce consistent standards
