### ISSUE TITLE
[ADDITION] numbr.dev

### ISSUE THREAD

**Issue by antonmedv** [Lissy93/awesome-privacy#62]
### Category

Utilities

### Software to be added

https://numbr.dev - notepad + calculator. 

### Supporting Material

https://github.com/antonmedv/numbr
https://chrome.google.com/webstore/detail/numbr/cncafkneilkicolelogcmmgblojmhfng
https://numbr.dev/ipbm

### Association Disclosure

I'm the author of the project

### Would you like to submit a PR?

Yes!

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Heya @antonmedv 

That's a really neat project! 

Is it actually open source though, as the repo seems to be missing a lot of the code. Maybe I'm looking in the wrong place, but it seems to only includes part of the parser.

**Comment by antonmedv** [comment]
Yes, and readme is missing) in process of cleaning ui to show it) but don’t know timeline yet. This is a problem of having too many open source projects))

**Comment by Lissy93** [comment]
> This is a problem of having too many open source projects

I can relate...

I'll wait until that's updated. Because I guess number.dev could also be self-hosted (right?), which is always nice to have as an option.

**Comment by antonmedv** [comment]
Bogus is okay) but I don’t know the time I be able to finish project. So…

**Comment by Lissy93** [comment]
No worries. When you're ready, just update me here, or submit a PR :)
