### ISSUE TITLE
[ADDITION] vaultwarden

### ISSUE THREAD

**Issue by baddate** [Lissy93/awesome-privacy#68]
### Category

Password Managers

### Software to be added

Alternative implementation of the Bitwarden server API written in Rust and compatible with [upstream Bitwarden clients](https://bitwarden.com/download/)*, perfect for self-hosted deployment where running the official resource-heavy service might not be ideal.

### Supporting Material

Github: https://github.com/dani-garcia/vaultwarden

### Association Disclosure

a user

### Would you like to submit a PR?

Yes!

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by SadMadLad** [comment]
Added via https://github.com/Lissy93/awesome-privacy/pull/108
