### ISSUE TITLE
[ADDITION] Betterbird email client

### ISSUE THREAD

**Issue by bambirombi** [Lissy93/awesome-privacy#82]
### Category

Email Clients

### Software to be added

Betterbird is better than Thunderbird in three ways: It contains new features exclusive to Betterbird, it contains bug fixes exclusive to Betterbird and it contains fixes that Thunderbird may ship at a later stage. 

### Supporting Material

https://www.betterbird.eu/
https://github.com/Betterbird/

### Association Disclosure

No

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Thanks @bambirombi 
I've added it :)
