### ISSUE TITLE
[ADDITION] Mojeek

### ISSUE THREAD

**Issue by PrivacyDingus** [Lissy93/awesome-privacy#87]
### Category

Search Engines

### Software to be added

Mojeek is a search engine based in the UK, unlike options currently on the list (which all have decent no-tracking privacy policies) Mojeek does not rely upon another index when it comes to providing people with general web search results. 

### Supporting Material

A good summary of Mojeek milestones is on Wikipedia - https://en.wikipedia.org/wiki/Mojeek
Current privacy policy - https://www.mojeek.com/about/privacy/
Original privacy policy (2006) according to those who have looked, the first of its kind - https://web.archive.org/web/20060318104627/http://www.mojeek.com/privacy.html
A look search engines and indexes - https://seirdy.one/posts/2021/03/10/search-engines-with-own-indexes/
An article which [cropped up in a previous issue](https://github.com/Lissy93/awesome-privacy/issues/24) which further explores some of the unique aspects of Mojeek - https://12bytes.org/articles/tech/alternative-search-engines-that-respect-your-privacy/

### Association Disclosure

I currently work at Mojeek

### Would you like to submit a PR?

_No_

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Hi Josh,

Thanks for the suggestion. I've played around with Mojeek, and would be happy to add it to the list. I've created a PR #91 - feel free to drop it a review.

---

I'd be interested in hearing others thoughts on this, so if anyone else has anything to add, please do! But a summary of my findings were:

**Pros**
- No ad integrations with Microsoft, Google, etc
- Android app has no trackers, and a single permission (internet access)
- Website makes no XHR requests, and there's no client-side tracking
- Privacy policy is very good
- Operates their own crawlers, not a meta search engine
- Claims to return unbiased results

**Cons**
- Not open source, so cannot verify there is no server-side tracking
- Based in the UK, which is part of the 5 Eyes
- Unclear where the investment came from
- Unclear revenue model (they have an ad program but doesn't seem widely used, they also have a paid API, but no sign up option)
- No image search, but do have the option to show Bing image results
- Lack of search features, compared to providers like DDG
- Sometimes buggy, some buttons don't work, some settings options seem unclear, and some expected results don't show up in search (probably to be expected from a smaller search engine)

**Comment by PrivacyDingus** [comment]
Thanks @Lissy93, and also for this list of Cons, which is something I'll add back into our feedback cycle. For bullet points 3 and 4 (apologies for the quantity of reading) this piece of [Who Funds Mojeek?](https://blog.mojeek.com/2020/10/who-funds-mojeek.html) and [this piece on Frequently Aasked Questions](https://blog.mojeek.com/2020/12/frequently-asked-questions-about-mojeek-business-model-surveillance-privacy.html) (which is outdated and we should look at again) may be of use.

**Comment by SadMadLad** [comment]
Already added via https://github.com/Lissy93/awesome-privacy/pull/91
