### ISSUE TITLE
[REMOVAL] RainLoop

### ISSUE THREAD

**Issue by ltGuillaume** [Lissy93/awesome-privacy#96]
### Title

RainLoop

### Removal Reason

- The RainLoop project is stale and hasn't been updated since May 6, 2021.
- There is a [known vulnerability](https://thehackernews.com/2022/04/unpatched-bug-in-rainloop-webmail-could.html) that allows access to all emails. This has not been patched in the official repository.
- Some mail services, like Disroot.org, have responded by migrating to an actively developed fork called [SnappyMail](https://snappymail.eu).

_On a side note: there's a typo in the template: "You have indicated ~~weather~~ whether or not you are associated with this project or a competitor"_

### Association Disclosure

None

### Would you like to submit a PR?

Yes!

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with this project or a competitor
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by ltGuillaume** [comment]
@Lissy93 Considering this is a major security concern, perhaps  a response? 😅

**Comment by Lissy93** [comment]
So sorry for the late reply. Have looked into this, and I agree, Rainloop should be removed.
Would you be up for submitting a PR? (no worries if not, I can do it this week)
